# Generated by Django 5.2.1 on 2025-09-26 14:41

import app.middleware
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('OT', 'Outpatient treatment'), ('IT', 'Inpatient treatment'), ('CS', 'Consulting services')], default='OT', max_length=2)),
                ('profile', models.CharField(choices=[('THER', 'Therapeutic'), ('THER_TH', 'Therapist'), ('THER_NE', 'Neurologist'), ('THER_CA', 'Сardiologist'), ('SURG', 'Surgical'), ('SURG_PH', 'Phlebologist'), ('DIAG', 'Diagnostical'), ('DIAG_RA', 'Radiologist'), ('DIAG_US', 'Ultrasound')], default='THER', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(default=app.middleware.get_current_user, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
