# Generated by Django 5.2.1 on 2025-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0002_alter_workplace_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='profile',
            field=models.CharField(choices=[('THER', 'Therapeutic'), ('THER_TH', 'Therapist'), ('THER_NE', 'Neurologist'), ('THER_CA', 'Сardiologist'), ('SURG', 'Surgical'), ('SURG_PH', 'Phlebologist'), ('DIAG', 'Diagnostical'), ('DIAG_RA', 'Radiologist'), ('DIAG_US', 'Ultrasound doctor')], default='THER', max_length=7),
        ),
        migrations.AddField(
            model_name='workplace',
            name='type',
            field=models.CharField(choices=[('OT', 'Outpatient treatment'), ('IT', 'Inpatient treatment'), ('CS', 'Consulting services')], default='OT', max_length=2),
        ),
    ]
